README.md
Coanda CMS is a content management system based on the Laravel PHP Framework.
=> Add CondaCMS Application

README.md
=> Added a Environment library.

README.md
Added [infinity-next/brennan-captcha](https://github.com/infinity-next/brennan-captcha) to Authentication/Security
=> Added infinity-next/brennan-captcha

README.md
Added my packages:
Captcha
[https://github.com/mewebstudio/captcha](https://github.com/mewebstudio/captcha)
Purifier
[https://github.com/mewebstudio/purifier](https://github.com/mewebstudio/purifier)
=> Added Captcha and HTMLPurifier

README.md
Advanced Laravel Login and User Management with Two-Factor Authentication
=> Added EasyAdmin

README.md
I would like to add this package in our list
=> Adding Tinify API support with Laravel Package

README.md
=> Remove Laramap

README.md
https://github.com/svenluijten/env-providers
=> Add env-providers

README.md
If you want me to add of our individual packages to the list, let me know.
=> Add Spatie packages

README.md
'Fluent-Facebook' package is a laravel 5 package for reading and writing to facebook graph object with ease in laravelish syntax
=> 'Fluent-Facebook' package added

README.md
=> Remove Kanban link

README.md
added [Orchid](https://theorchid.github.io/en/) admin panel
=> Orchid admin panel

README.md
Add service that allows to log every HTTP request/response and UI to search and analyze.
=> Add service to log and analyze http requests

README.md
Add Themevel Package for Laravel Theme Management
https://github.com/shipu/themevel
=> Add Themevel Package for Laravel Theme Management

README.md
Added laravel-widgetize to Design Pattern Tools section on \[4/4/2017\]
=> Added laravel-widgetize

README.md
See also:
- https://demo.userfrosting.com
- https://learn.userfrosting.com
- https://chat.userfrosting.com
=> Add UserFrosting to Admin Tools/Panels

README.md
Hi,
Hopefully it's OK to add this to the top of the list. I wasn't sure, but I checked some other pull requests and it seems to be the norm'.
In any case, if there's anything I can update here, please let me know. Cool list!
=> Add Getting Started with Pusher and Laravel Echo tutorial

README.md
Moves all "Documentation" from Controllers/Models and App related code to a config file.
=> Added Open API for laravel

README.md
I made a Laravel UI preset for UIkit that I think would be a good fit for your list
=> Add UIkit UI preset

README.md
Hey @TimothyDJones 
just removing a dead link to TinyLara - turned into a Chinese Casino...
Cheers!
=> Removing "TinyLara"

README.md
Is a user impersonate for the Laravel Framework. allow a developer direct login as another user during development quickly with GUI.
=> Add LaraPersonate - User Impersonate With GUI.

README.md
Package to fire events on attribute changes of your Eloquent model.
=> Add Attribute Events

README.md
https://github.com/ucan-lab/docker-laravel
=> Add docker-laravel

README.md
bugphix - Capture and monitor detailed error logs with nice dashboard and UI
=> added new package - bugphix
